---
logs:
  json: false
metrics:
  endpoint: 127.0.0.1:10124
channel:
  tokio:
    worker_threads: null # by default number of cpus
    affinity: null # by default no affinity (taskset syntax)
  sources_sighup_reload: false # if `true`, SIGHUP reload sources from the config
  sources:
    - name: plugin-shm
      parser: raw # valid: prost, limited
      disable_accounts: false
      reconnect: null
      channel_size: 16384
      shm:
        path: /dev/shm/richat
      # pre_filter:
      #   bloom_accounts:
      #     - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
  config:
    max_messages: 2_097_152
    max_bytes: 16GiB
    # storage:
    #   path: ./db
    #   max_slots: 1024
    #   serialize_affinity: null # taskset syntax
    #   write_affinity: null
    #   messages_compression: none # none, snappy, zlib, bz2, lz4, lz4hc, zstd
apps:
  tokio:
    worker_threads: null # by default number of cpus
    affinity: null # by default no affinity (taskset syntax)
  # richat:
  #   shm:
  #     path: /dev/shm/richat
  #     max_messages: 2097152
  #     max_bytes: 15GiB
